name: Wake Streamlit App Daily

on:
  schedule:
    - cron: '0 6 * * *'  # Once daily at 6:00 AM UTC
  workflow_dispatch:

jobs:
  wake-streamlit:
    runs-on: ubuntu-latest
    steps:
      - name: Wait before pinging (optional)
        run: sleep 30  # Waits for 30 seconds (adjust if needed)

      - name: Wake Streamlit app with browser-style curl
        run: |
          echo "Waking Streamlit app at https://yencarrytrade.streamlit.app/"

          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" \
            -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64)" \
            https://yencarrytrade.streamlit.app/)

          echo "HTTP status: $HTTP_STATUS"

          if [ "$HTTP_STATUS" -eq 200 ]; then
            echo "✅ Streamlit app is awake and responsive."
          else
            echo "❌ Failed to wake Streamlit app. HTTP status: $HTTP_STATUS"
            exit 1
          fi
