# .github/workflows/ping_streamlit.yml
name: Ping Streamlit App Twice Daily

on:
  schedule:
    - cron: '0 */12 * * *'  # Every 12 hours
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping the Streamlit app
        run: curl -sSL https://yencarrytrade.streamlit.app/
